# Generated by Django 5.1.6 on 2025-03-19 15:57

import apps.user.models
import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('web_name', models.CharField(blank=True, max_length=128, verbose_name='网站名称')),
                ('header_inform', models.CharField(blank=True, max_length=128, verbose_name='头部通知')),
                ('aside_inform', models.CharField(blank=True, max_length=128, verbose_name='侧面公告')),
                ('web_time', models.DateTimeField(default=None, verbose_name='网站创建时间')),
                ('archival_inform', models.CharField(blank=True, max_length=128, verbose_name='备案信息')),
                ('slideshow', models.CharField(blank=True, max_length=128, verbose_name='轮播图')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('nick_name', models.CharField(blank=True, max_length=128, verbose_name='昵称')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='头衔')),
                ('avatar', models.CharField(blank=True, max_length=128, verbose_name='头像')),
                ('bg_img', models.CharField(blank=True, max_length=128, verbose_name='背景图')),
                ('github_url', models.CharField(blank=True, max_length=128, verbose_name='github地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('web_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.webinfo', verbose_name='网站信息')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'system_user',
            },
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
    ]
