# Generated by Django 5.1.6 on 2025-03-19 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_webinfo_options_alter_user_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='web_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 19, 16, 3, 49, 533578), null=True, verbose_name='网站创建时间'),
        ),
    ]
