# Generated by Django 5.1.6 on 2025-03-19 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_webinfo_web_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='web_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='网站创建时间'),
        ),
    ]
