# Generated by Django 5.1.6 on 2025-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_webinfo_web_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='slideshow',
            field=models.TimeField(blank=True, verbose_name='轮播图'),
        ),
    ]
