# Generated by Django 5.1.6 on 2025-03-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_webinfo_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='slideshow',
            field=models.TextField(blank=True, verbose_name='轮播图'),
        ),
    ]
