# Generated by Django 5.1.6 on 2025-03-31 18:28

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='主键')),
                ('article_content', models.TextField(verbose_name='文章内容')),
                ('article_title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='文章分类')),
                ('article_tags', models.ManyToManyField(to='tag.tag', verbose_name='文章标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'sakura_article',
                'ordering': ['-create_time'],
            },
        ),
    ]
